### PR TITLE
src|cmake: Fix some `FromBytes` decoding issues, add more test cases

### PR DESCRIPTION
**Pull request by xdustinface**
This is a (i think the proper) fix for #251 which basically has been introduced by a bug-fix in relic, see https://github.com/relic-toolkit/relic/commit/c7177c87118333db166175fe635b953cea8d8c58 and https://github.com/relic-toolkit/relic/issues/206. Please also have a look here @dfaranha :)

a90d56a expands the test case to cover the issue detected in #251 and e9f60d1 is the actual fix.

### CODE REVIEW

**Review by hoffmang9 — APPROVED** [review]
lgtm

**Comment by xdustinface** [comment]
Okay, turned out that there are more "first byte values" where it should pass because the 4 lower bits of the first byte are also used as data. I adjusted the test and fixed an issue in the zero bytes check.. now it should have the same behavior like before the relic bug-fix which introduced the change of the behavior. But at the end i guess this should also be fixed in relic itself @dfaranha?

Another thing i realized is that with this commit https://github.com/relic-toolkit/relic/commit/1620a03b388e50acd68ed9c88d7cd82ec5490ce4 we get more invalid cases, see 1fa53dc91a30b90f007f0991c8c3189dc0e9db43 which is required after that commit . I miss some background here to judge if all of the values in here 
```
0x85, 0x86, 0x87, 0x88, 0x89, 0x8C, 0x8F, 0x91, 0x93, 0x94, 0x96, 0x98, 0x99, 0x9A, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAC, 0xAF, 0xB1, 0xB3, 0xB4, 0xB6, 0xB8, 0xB9, 0xBA
```

with zeroes appended should be decoded to valid G1 elements. Can either of you @mariano54 or @dfaranha share your thoughts?

Also just for the record, this PR now bumps relic to https://github.com/relic-toolkit/relic/commit/b7b2266a0e4ee6f628f61d3ab638f524a18b52f1. If someone has any objections let me know, i can then drop 1fa53dc91a30b90f007f0991c8c3189dc0e9db43 and 896e33c5210a7272280a72a218d2468a377d97df.

**Comment by dfaranha** [comment]
Currently on holidays, but will catch-up tonight!

**Comment by mariano54** [comment]
I have not reviewed this yet

**Comment by wjblanke** [comment]
ah i saw gene's review and thought it had gone through

**Comment by hoffmang9** [comment]
Sorry - however it did pass Guido's testing and it looked otherwise correct - which is why I approved.

**Review by mariano54 — COMMENTED** [review]
LGTM

**Pull request merged**
