### PR TITLE
Updates to cmake to work around missing statics

### PR DESCRIPTION
**Pull request by emlowe**
Setup CMAKE to require C++17 - this helps with places where the default compiler does not (Centos 7) and errors out early
Also, configure to avoid making the "combined custom" library libbls.a if the platform does not have the static versions of libgmp or libsodium. The library and test programs still work, however, because the dynamic version will be linked to the executable (ie runtest, etc)
This does mean on such a system that when using libbls.a one does need to link to the dynamic libraries, but this is preferable to not building at all and throwing strange errors. This should fix issue #225

### CODE REVIEW

**Review by hoffmang9 — APPROVED** [review]
lgtm

**Comment by emlowe** [comment]
I also made a small change for 32-bit systems (which are actually pretty rare now - most common Linux distros don't support them anymore).
Tested on Centos7 32-bit
Tested on Centos7 64-bit

**Review by hoffmang9 — APPROVED** [review]
Nice add

**Review by hoffmang9 — APPROVED** [review]
AOK

**Pull request merged**
