### PR TITLE
Added option to disable bindings

### PR DESCRIPTION
**Pull request by mxaddict**
This is for when you only want to build for c/c++ linking

### CODE REVIEW

**Comment by hoffmang9** [comment]
The problem with your method is that the primary use of this library is to build python wheels. I'd suggest that the better path would be to add an environment variable check like C_ONLY, at that to the documentation, and have CMake check for that.

**Comment by mxaddict** [comment]
> The problem with your method is that the primary use of this library is to build python wheels. I'd suggest that the better path would be to add an environment variable check like C_ONLY, at that to the documentation, and have CMake check for that.

I think I understand what you mean, but I'm not familiar with CMake syntax for checking env vars.

I'll have to do some googling and re-create this PR later 😄

**Comment by mxaddict** [comment]
> The problem with your method is that the primary use of this library is to build python wheels. I'd suggest that the better path would be to add an environment variable check like C_ONLY, at that to the documentation, and have CMake check for that.

BTW, quick question, I noticed other code in contribs are git subtrees but pybind is a submodule any particular reason for this?

**Comment by hoffmang9** [comment]
Yes. Unfortunately we had to mangle relic and catch is fairly static. We use pybind in bone stock upstream. Relic is moving closer to our mangling though so we'll be trying to upstream it in the next release which is real soon now. Pybind can be pulled in as a submodule or CMake will download it if you're not using git (think compiling this library under a python install in Rasberry Pi.)

**Comment by hoffmang9** [comment]
See - https://cmake.org/cmake/help/latest/variable/ENV.html

**Comment by mxaddict** [comment]
I'll close this for now, will re-open once I've got the time.

**Pull request closed without merging**
