### PR TITLE
Build on main, tags, and PRs

### PR DESCRIPTION
**Pull request by altendky**
As is this builds on any push and also any PR.  This results in double workflows on PRs.

### CODE REVIEW

**Comment by altendky** [comment]
When reviewing, please consider how releases are done.  I do not know this process and as such don't know how it might affect it.  Mostly this should just stop the double builds and add builds on tags.

**Review by cmmarslender — APPROVED** [review]
Seems ok to me - I think the only real change here is just not running on pushes to branches other than main without a PR being open - otherwise, should run in all the existing cases.

**Comment by altendky** [comment]
That, plus it will run on tags.

**Comment by cmmarslender** [comment]
> That, plus it will run on tags.

Should have already been running on tags, since tags is within `push`, and push (with no further restrictions) was already selected before (this is also how releases happen - when the event was for a tag push)

**Pull request merged**
