### PR TITLE
Add Go bindings for C++ library

### PR DESCRIPTION
**Pull request by nmarley**
Hi! I'm Nathan, I am a developer for Dash, where we are users of this library in our Core daemon. We had a need for Go bindings for this for some other projects, so I wrote this and hope it can be useful for others.

This wraps the C++ calls in a C interface which CGo is then able to use. I have included instructions for building and use, and linked to an external example Go project. I look forward to any feedback! Thanks.

### CODE REVIEW

**Comment by nmarley** [comment]
If this does get merged, I will follow up w/a PR to update the documentation to point to this repo instead of my own, and that will allows the install instructions to be accurate both now and in the future.

**Comment by mariano54** [comment]
Thank you! are these binding being maintained?

**Comment by nmarley** [comment]
Hi Mariano! I wrote these over the past few weeks and just PR'd not too long ago, but currently yes, I am the maintainer. (Unless I'm misunderstanding your question.)

Is there something else you'd like to see?

**Comment by mariano54** [comment]
Thanks. Yes, as long as there is an active maintainer that can respond to issues that people may have, it's fine. I plan to merge it after review.

**Comment by crossle** [comment]
When merge the PR?

**Comment by hoffmang9** [comment]
This PR is out of date and references the pre IETF standard version of the library. Anyone who could bring it up to date would be appreciated.

**Comment by mariano54** [comment]
Closing this due to changes that have occurred in the library.

**Pull request closed without merging**
