### PR TITLE
Add functions to Python binding to support pairing cache

### PR DESCRIPTION
**Pull request by rostislav**

### CODE REVIEW

**Review by xdustinface — COMMENTED** [review]
@rostislav Looks good but one question. Wouldn't it make sense to only partially revert 4a1013a and keep `BNWrapper` dropped or do you also need it for something?

**Comment by rostislav** [comment]
@xdustinface I agree that `BNWrapper` could be dropped. I'll prepare an update for this.

**Comment by rostislav** [comment]
I've removed `BNWrapper` and added some tests for the new functions.

**Review by xdustinface — CHANGES_REQUESTED** [review]
@rostislav I just realized there is even more code we should not revert. See 7615e4ff3430d791a7aaf85f9e326b1848e2c90c.

**Review by xdustinface — APPROVED** [review]

**Pull request merged**
